version: '2'
 
services:
  app:
    environment:
      - MeetupApiKey
    build:
      context:  ./src/DataDrivenDiversity
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  nlp:
    build:
      context:  ./nlp
      dockerfile: Dockerfile
    ports:
      - "6000:5000"
    links:
      - app
