version: '2'
 
services:
  # nlp:
  #   image: larenedevregistry.azurecr.io/meetups-nlp
  #   build:
  #     context: ./nlp
  #     dockerfile: Dockerfile
  #   hostname: nlp
  #   ports:
  #     - "6000:5000"

  ner:
    image: frnkenstien/corenlp
    hostname: ner
    ports:
      - "9000:9000"

  seq:
    image: datalust/seq:latest
    hostname: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  # db:
  #   image: couchdb:latest
  #   hostname: db
  #   ports:
  #     - "5984:5984"