version: '2'
 
services:
  app:
    image: larenedevregistry.azurecr.io/meetups-app
    environment:
      - MeetupApiKey
    build:
      context:  ./src/DataDrivenDiversity
      dockerfile: Dockerfile
    hostname: app
    ports:
      - "8080:80"
    links:
      - nlp

  nlp:
    image: larenedevregistry.azurecr.io/meetups-nlp
    build:
      context: ./nlp
      dockerfile: Dockerfile
    hostname: nlp
    ports:
      - "6000:5000"
    expose:
      - "5000"
